routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Admin', 'as' => 'admin.'], function () {

    Auth::routes();

    Route::group(['middleware' => 'auth:admin'], function () {
        Route::get('/', function () { return redirect()->route('admin.dashboard'); });
        Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
        Route::get('/profile/edit', 'ProfileController@edit')->name('profile.self-edit');
        Route::post('/profile/update', 'ProfileController@update')->name('profile.self-update');
        Route::get('/profile/password', 'ProfileController@password')->name('profile.password');
        Route::post('/profile/updatePassword', 'ProfileController@updatePassword')->name('profile.updatePassword');
        Route::resource('/profile', 'ProfileController');

        Route::resource('/car-models', 'CarModelController');
        Route::get('/api/get-cars', 'CarsController@availableCars');

        Route::post('/drivers/getPaymentDetails', 'DriversController@getPaymentDetails')->name('DriversController.getPaymentDetails');
        Route::resource('/drivers', 'DriversController');
        Route::resource('/cars', 'CarsController');

        Route::resource('/service-pricing', 'ServicePricingController');
        Route::post('/service-pricing/updateGlobalSetting', 'ServicePricingController@updateGlobalSetting')->name('ServicePricingController.updateGlobalSetting');
        Route::post('/service-pricing/updatePrice', 'ServicePricingController@updatePrice')->name('ServicePricingController.updatePrice');
        Route::post('/service-pricing/updateAdditionalPrice', 'ServicePricingController@updateAdditionalPrice')->name('ServicePricingController.updateAdditionalPrice');
        Route::post('/service-pricing/addAdditionalPrice', 'ServicePricingController@addAdditionalPrice')->name('ServicePricingController.addAdditionalPrice');
        Route::delete('/service-pricing/additionalPriceDestroy/{id}', 'ServicePricingController@additionalPriceDestroy')->name('ServicePricingController.additionalPriceDestroy');

        Route::resource('/client', 'ClientController');

        Route::get('/merchant/{id}/contact', 'MerchantController@contact')->name('merchant.contact');
        Route::post('/merchant/{id}/contact', 'MerchantController@contactStore');
        Route::resource('/merchant', 'MerchantController');

        Route::post('/package/package-image-upload', 'PackageController@packageImageUpload')->name('package.packageImageUpload');
        Route::get('/package/{id}/image-video-upload', 'PackageController@imageVideoUpload')->name('package.imageVideoUpload');
        Route::resource('/package', 'PackageController');

        Route::resource('/service-setting', 'ServiceSettingController');

        Route::get('/booking/booking-bid-list', 'BookingController@bookingBidList')->name('booking.bookingBidList');
        Route::get('/booking/booking-cancelled-list', 'BookingController@bookingCancelledList')->name('booking.bookingCancelledList');
        Route::post('/booking/assign-driver/{booking_id}', 'BookingController@assignDriver')->name('booking.assign-driver');
        Route::resource('/booking', 'BookingController');

        // Report Routes Start
        Route::get('/report/receivable', 'ReportController@index');
        Route::get('/report/payable', 'ReportController@payable');
        Route::get('/report/income', 'ReportController@income');
        Route::get('/report/expense', 'ReportController@expense');
        Route::get('/report/profit-loss', 'ReportController@profitLoss');
        // Report Routes End

        Route::get('/bidding-trips/bids/{bidding_trip_id}', 'BiddingTripController@bids')->name('bidding-trips.bids');
        Route::post('/bidding-trips/bid/{id}', 'BiddingTripController@submitBid')->name('bidding-trips.submit-bid');
        Route::resource('/bidding-trips', 'BiddingTripController')->only('index', 'show', 'delete');

        Route::resource('/expense-category', 'ExpenseCategoryController');
        Route::resource('/expense', 'ExpenseController');

        Route::get('/crm/calling', 'CrmController@calling');
        Route::get('/crm/followup', 'CrmController@followup');
        Route::resource('/crm', 'CrmController');

        Route::resource('/sms', 'SmsController');

        Route::resource('/contact-mail', 'ContactMailController');

        // CMS Routes Start
        Route::resource('/tourism', 'TourismController');
        Route::resource('/management', 'ManagementController');
        Route::resource('/slide', 'SlideController');
        Route::resource('/career', 'CareerController');
        Route::resource('/news', 'NewsController');
        Route::resource('/policy', 'PolicyController');
        Route::resource('/contact-type', 'ContactTypeController');
        Route::resource('/seo', 'SeoController');
        Route::resource('/web-settings', 'WebSettingController');
        // CMS Routes End
    });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['namespace' => 'Web'], function () {
    // Pages Routes Start
    Route::get('/', 'PagesController@index')->name('home');
    Route::get('/home', 'PagesController@index')->name('home');
    Route::get('/about-us', 'PagesController@aboutUs')->name('about-us');
    Route::get('/fleet', 'PagesController@fleet')->name('fleet');
    Route::get('/management-team', 'PagesController@management')->name('management-team');
    Route::get('/careers', 'PagesController@careers')->name('careers');
    Route::get('/news', 'PagesController@news')->name('news');
    Route::get('/news/{slug}','PagesController@news')->name('news');
    Route::get('/contact-us', 'PagesController@contactUs')->name('contact-us');
    Route::post('/contact-send-mail', 'PagesController@contactSendMail')->name('contact-send-mail');
    Route::get('/cancellation-policy', 'PagesController@cancellationPolicy')->name('cancellation-policy');
    Route::get('/wait-time-policy', 'PagesController@waitTimePolicy')->name('wait-time-policy');
    Route::get('/privacy-policy', 'PagesController@privacyPolicy')->name('privacy-policy');
    Route::get('/refund-and-return-policy', 'PagesController@refundPolicy')->name('refund-and-return-policy');
    Route::get('/terms-and-conditions', 'PagesController@termsConditions')->name('terms-and-conditions');
    Route::get('/faq', 'PagesController@faq')->name('faq');
    Route::get('/sitemap', 'PagesController@sitemap')->name('sitemap');
    Route::get('/partner-with-us', 'PagesController@partnerWithUs')->name('partner-with-us');
    Route::post('/partner-make', 'PagesController@partnerMade')->name('partner-make');
    Route::get('/services', 'PagesController@services')->name('services');
    // Pages Routes End

    Route::get('/api/google/autocomplete', 'Api\GoogleApiController@autocomplete');
    Route::get('/api/google/place-details', 'Api\GoogleApiController@getPlaceDetails');
    Route::get('/api/google/reverse', 'Api\GoogleApiController@getReversePlaceDetails');

    Route::get('/api/get-car-models', 'CarController@getCarByVehicleType');

    Route::get('/api/get-airport-cities', 'AirportController@getCities');

    Route::get('/api/get-upazila', 'UpazilaBoundaryController@index')->name('upazila.index');
    Route::get('/api/get-upazila-select2', 'UpazilaBoundaryController@getUpazilaNameSelect2')->name('upazila.getUpazilaNameSelect2');
    Route::get('/api/get-upazilas-by-upazila-boundary-ids', 'UpazilaBoundaryController@getUpazilasByUpazilaBoundaryIds')->name('upazila.getUpazilaNameSelect2');
});

Route::group(['namespace' => 'User'], function () {
    Route::get('/service-categories', 'ServiceController@getServiceCategoryList');
    Route::get('/services-by-category/{id}', 'ServiceController@getServicesList');
    Route::post('/search-for-car', 'ServiceController@fetchServicePricingByCustomerRequest');
    Route::get('/check-auth-booking/{value}', 'ServiceController@checkAuthUserForBooking');
    Route::get('/booking-details/{booking_type}', 'ServiceController@bookingConfirmation')->name('booking.details');
    Route::group(['middleware' => 'auth'], function () {
        Route::post('/booking-confirm', 'BookingController@bookingConfirmationDetails')->name('booking.confirm');
        Route::patch('/update-profile', 'AccountsController@update_profile');

        Route::group(['as' => 'user.'], function () {
            Route::get('/account/bookings', 'AccountsController@bookings')->name('bookings');
            Route::get('/account/my-profile', 'AccountsController@myProfile');
            Route::get('/account/profile', 'AccountsController@profile')->name('profile');
            Route::get('/account', 'AccountsController@index')->name('account');

            Route::post('/bookings/update-status/{booking_id}', 'BookingController@updateStatus');
            Route::resource('/bookings', 'BookingController');
            Route::resource('/bids', 'BidController')->only('show');
            Route::resource('/bidding-trips', 'BiddingTripController')->only('index', 'show', 'store');
            Route::resource('/payments', 'PaymentController');
        });
    });

    Route::get('/transaction-success', 'PaymentMessageController@success')->name('transaction.success');
    Route::get('/transaction-failed', 'PaymentMessageController@failed')->name('transaction.failed');

    // SSLCOMMERZ Start
    Route::post('/pay', 'SslCommerzPaymentController@index');

    Route::post('/success', 'SslCommerzPaymentController@success');
    Route::post('/fail', 'SslCommerzPaymentController@fail');
    Route::post('/cancel', 'SslCommerzPaymentController@cancel');

    Route::post('/ipn', 'SslCommerzPaymentController@ipn');
    //SSLCOMMERZ END

    // Vue JS Route
    // Route::get('/{any}', 'HomeController@index')->where('any', '.*');
});

resources/views/admin/layouts/inc/navbar.blade.php
<nav class="navbar navbar-static-top" role="navigation">
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </a>

    <span class="project-name-header"></span>

    <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">

            <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <img src="{{ (Auth::user()->image!='')?asset('uploads/users/thumb_'.Auth::user()->image):asset('admin-assets/img/avatar.png') }}" class="user-image" alt="{{ Auth::user()->name }}">
                    <span class="hidden-xs">
                        {{ Auth::user()->name }}
                    </span>
                </a>

                <ul class="dropdown-menu">
                    <li class="user-header">
                        <img src="{{ (Auth::user()->image!='')?asset('uploads/users/thumb_'.Auth::user()->image):asset('admin-assets/img/avatar.png') }}" class="img-circle" alt="{{ Auth::user()->name }}">
                        <p>
                            {{ Auth::user()->name }}
                            <small>
                                {{ Auth::user()->email }}
                            </small>
                        </p>
                    </li>

                    <li class="user-footer">
                        <div class="pull-left">
                            <a class="btn btn-default btn-flat" href="{{route('admin.profile.index')}}">Profile</a>
                        </div>
                        <div class="pull-right">
                            <a class="btn btn-default btn-flat" href="{{ route('admin.logout') }}"
                               onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" class="non-validate" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</nav>

resources/views/admin/layouts/inc/sidebar.blade.php
<aside class="main-sidebar">
    <section class="sidebar">
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{ (Auth::user()->image!='')?asset('uploads/users/thumb_'.Auth::user()->image):asset('admin-assets/img/avatar.png') }}" class="img-circle" alt="{{ Auth::user()->name }}">
            </div>
            <div class="pull-left info">
                <p>{{ Auth::user()->name }}</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        <ul class="sidebar-menu">
            <li class="header" style="padding:2px;"></li>
            <li class="treeview">
                <a href="#"><i class="fa fa-handshake-o"></i> <span>Cars & Drivers</span> <i class="fa fa-angle-left pull-right"></i></a>
                <ul class="treeview-menu">
                    <li id="menu_partner">
                        <a href="{{url('/admin/cars')}}">
                            <i class="fa fa-arrow-right"></i>
                            <span>Cars</span>
                        </a>
                    </li>
                    <li id="menu_partner_car">
                        <a href="{{url('/admin/car-models')}}">
                            <i class="fa fa-arrow-right"></i>
                            <span>Car Models</span>
                        </a>
                    </li>
                    <li id="menu_partner_car">
                        <a href="{{url('/admin/drivers')}}">
                            <i class="fa fa-arrow-right"></i>
                            <span>Drivers</span>
                        </a>
                    </li>
                </ul>
            </li>

            <li>
                <a href="{{url('/admin/client')}}">
                    <i class="fa fa-users"></i>
                    <span>Client</span>
                </a>
            </li>

            <li class="treeview">
                <a href="#"><i class="fa fa-handshake-o"></i> <span>Merchants</span> <i class="fa fa-angle-left pull-right"></i></a>
                <ul class="treeview-menu">
                    <li id="menu_merchant">
                        <a href="{{url('/admin/merchant')}}">
                            <i class="fa fa-arrow-right"></i>
                            <span>Merchants</span>
                        </a>
                    </li>
                </ul>
            </li>

            <li class="treeview">
                <a href="#"><i class="fa fa-car"></i> <span>Booking</span> <i class="fa fa-angle-left pull-right"></i></a>
                <ul class="treeview-menu">
                    <li>
                        <a href="{{url('admin/booking/create')}}">
                            <i class="fa fa-arrow-right"></i>
                            <span>New Booking</span>
                        </a>
                    </li>

                    <li>
                        <a href="{{url('/admin/booking')}}">
                            <i class="fa fa-arrow-right"></i>
                            <span>Booking List</span>
                        </a>
                    </li>

                    <li>
                        <a href="{{url('/admin/booking/booking-bid-list')}}">
                            <i class="fa fa-arrow-right"></i>
                            <span>Booking Bid List</span>
                        </a>
                    </li>

                    <li>
                        <a href="{{url('/admin/bidding-trips')}}">
                            <i class="fa fa-arrow-right"></i>
                            <span>Bidding Trip List</span>
                        </a>
                    </li>

                    <li>
                        <a href="{{url('/admin/booking/booking-cancelled-list')}}">
                            <i class="fa fa-arrow-right"></i>
                            <span>Cancelled Trips</span>
                        </a>
                    </li>

                    <li>
                        <a href="{{url('/admin/service-setting')}}">
                            <i class="fa fa-arrow-right"></i>
                            <span>Cancelled Booking</span>
                        </a>
                    </li>

                    <li>
                        <a href="{{url('/admin/service-setting')}}">
                            <i class="fa fa-arrow-right"></i>
                            <span>Payment Pending</span>
                        </a>
                    </li>

                    <li>
                        <a href="{{url('/admin/service-setting')}}">
                            <i class="fa fa-arrow-right"></i>
                            <span>Payment Cancelled</span>
                        </a>
                    </li>

                    <li>
                        <a href="{{url('/admin/service-setting')}}">
                            <i class="fa fa-arrow-right"></i>
                            <span>Failed to Pay</span>
                        </a>
                    </li>
                </ul>
            </li>

            <li class="treeview">
                <a href="#"><i class="fa fa-bar-chart"></i> <span>Report</span> <i class="fa fa-angle-left pull-right"></i></a>
                <ul class="treeview-menu">
                    <li id="menu_report_receivable">
                        <a href="{{url('/admin/report/receivable')}}">
                            <i class="fa fa-arrow-right"></i>
                            <span>Amount Receivable</span>
                        </a>
                    </li>
                    <li id="menu_report_payable">
                        <a href="{{url('/admin/report/payable')}}">
                            <i class="fa fa-arrow-right"></i>
                            <span>Amount Payable</span>
                        </a>
                    </li>
                    <li id="menu_report_income">
                        <a href="{{url('/admin/report/income')}}">
                            <i class="fa fa-arrow-right"></i>
                            <span>Income (Commission)</span>
                        </a>
                    </li>
                    <li id="menu_report_expense">
                        <a href="{{url('/admin/report/expense')}}">
                            <i class="fa fa-arrow-right"></i>
                            <span>Expenses</span>
                        </a>
                    </li>
                    <li id="menu_report_profit-loss">
                        <a href="{{url('/admin/report/profit-loss')}}">
                            <i class="fa fa-arrow-right"></i>
                            <span>Net Income</span>
                        </a>
                    </li>
                </ul>
            </li>

            <li class="treeview">
                <a href="#"><i class="fa fa-coffee"></i> <span>Expense</span> <i class="fa fa-angle-left pull-right"></i></a>
                <ul class="treeview-menu">
                    <li id="menu_expense">
                        <a href="{{url('/admin/expense')}}">
                            <i class="fa fa-arrow-right"></i>
                            <span>Expense</span>
                        </a>
                    </li>
                    <li id="menu_expense_category">
                        <a href="{{url('/admin/expense-category')}}">
                            <i class="fa fa-arrow-right"></i>
                            <span>Expense Category</span>
                        </a>
                    </li>
                </ul>
            </li>

            <li class="treeview">
                <a href="#"><i class="fa fa-user-circle"></i> <span>CRM</span> <i class="fa fa-angle-left pull-right"></i></a>
                <ul class="treeview-menu">
                    <li id="menu_crm">
                        <a href="{{url('/admin/crm')}}">
                            <i class="fa fa-arrow-right"></i>
                            <span>CRM</span>
                        </a>
                    </li>
                    <li id="menu_crm_followup">
                        <a href="{{url('/admin/crm/followup')}}">
                            <i class="fa fa-arrow-right"></i>
                            <span>Followup</span>
                        </a>
                    </li>
                </ul>
            </li>

            <li id="menu_sms">
                <a href="{{url('/admin/sms')}}">
                    <i class="fa fa-comment-o"></i>
                    <span>SMS</span>
                </a>
            </li>

            <li id="menu_contact-mail">
                <a href="{{url('/admin/contact-mail')}}">
                    <i class="fa fa-envelope"></i>
                    <span>Contact Mail</span>
                </a>
            </li>

            <li class="treeview">
                <a href="#"><i class="fa fa-cogs"></i> <span>Service Setting</span> <i class="fa fa-angle-left pull-right"></i></a>
                <ul class="treeview-menu">
                    <li>
                        <a href="{{url('/admin/package')}}">
                            <i class="fa fa-arrow-right"></i>
                            <span>Packages</span>
                        </a>
                    </li>

                    <li>
                        <a href="{{url('/admin/service-setting')}}">
                            <i class="fa fa-arrow-right"></i>
                            <span>Service Pricing</span>
                        </a>
                    </li>
                </ul>
            </li>

            <li class="treeview">
                <a href="#"><i class="fa fa-globe"></i> <span>Website</span> <i class="fa fa-angle-left pull-right"></i></a>
                <ul class="treeview-menu">
                    <li id="menu_tourism">
                        <a href="{{url('/admin/tourism')}}">
                            <i class="fa fa-rocket"></i>
                            <span>Tourism</span>
                        </a>
                    </li>
                    <li id="menu_management">
                        <a href="{{url('/admin/management')}}">
                            <i class="fa fa-arrow-right"></i>
                            <span>Management</span>
                        </a>
                    </li>
                    <li id="menu_career">
                        <a href="{{url('/admin/career')}}">
                            <i class="fa fa-arrow-right"></i>
                            <span>Career</span>
                        </a>
                    </li>
                    <li id="menu_news">
                        <a href="{{url('/admin/news')}}">
                            <i class="fa fa-arrow-right"></i>
                            <span>News</span>
                        </a>
                    </li>
                    <li id="menu_policy">
                        <a href="{{url('/admin/policy')}}">
                            <i class="fa fa-arrow-right"></i>
                            <span>Page & Policy</span>
                        </a>
                    </li>
                    <li id="menu_contact-type">
                        <a href="{{url('/admin/contact-type')}}">
                            <i class="fa fa-arrow-right"></i>
                            <span>Contact Type</span>
                        </a>
                    </li>
                    <li id="menu_slide">
                        <a href="{{url('/admin/slide')}}">
                            <i class="fa fa-arrow-right"></i>
                            <span>Slide</span>
                        </a>
                    </li>
                    <li id="menu_seo">
                        <a href="{{url('/admin/seo')}}">
                            <i class="fa fa-arrow-right"></i>
                            <span>SEO</span>
                        </a>
                    </li>
                    <li id="menu_web_settings">
                        <a href="{{url('/admin/web-settings')}}">
                            <i class="fa fa-arrow-right"></i>
                            <span>Website Settings</span>
                        </a>
                    </li>
                </ul>
            </li>

        </ul>
    </section>
</aside>